on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm asp patch
      - name: Fix git unsafe repository
        run: git config --global --add safe.directory /__w/archriscv-packages/archriscv-packages
      - uses: actions/checkout@v2
      - name: Add remote
        run: |
          git remote add upstream https://github.com/felixonmars/archriscv-packages.git
          git fetch upstream master
      - name: Test patch
        run: bash test.sh
