on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm git patch subversion binutils
      - name: Fix git unsafe repository
        run: git config --global --add safe.directory /__w/archriscv-packages/archriscv-packages
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        run: |
          git remote add upstream https://github.com/felixonmars/archriscv-packages.git
          git fetch upstream master
      - name: Test patch
        run: bash test.sh
      - name: Upload patch.rej
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: patch.rej
          path: '**/*.rej'
          if-no-files-found: ignore
